services:
  # Backend API
  backend:
    build: ./backend
    container_name: khaocook-backend
    ports:
      - "3000:3000"
    environment:
      # *** อัปเดต DATABASE_URL ให้ชี้ไปที่ Cloud SQL Public IP ***
      # User: khaocook-first-project
      # Password: panitta04032547
      # IP: 136.110.48.92
      - DATABASE_URL=postgresql://khaocook-first-project:panitta04032547@136.110.48.92:5432/khaocook_db
      - NODE_ENV=production
    networks:
      - khaocook-network

  # Frontend (Nginx)
  frontend:
    image: nginx:alpine
    container_name: khaocook-nginx
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - khaocook-network


networks:
  khaocook-network:
    driver: bridge